/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package OpcionesEmergentes;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import paint.CustomDrawPanel;

/**
 *
 * @author alex5
 */
public class Relleno extends javax.swing.JDialog {

    private CustomDrawPanel drawPanel;
    

    public Relleno(java.awt.Frame parent, boolean modal,CustomDrawPanel drawPanel) {
        
        super(parent, modal);
        this.drawPanel = drawPanel;
        initComponents();
        this.setLocationRelativeTo(null);
        OpcionrellenoImage.setVisible(false);
    }

    Relleno(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OpcionrellenoImage = new javax.swing.JCheckBox();
        OpcionRellenoDeg = new javax.swing.JCheckBox();
        Opcionrelleno = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PrevisualizarColor = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PFin = new javax.swing.JPanel();
        PIncio = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpcionrellenoImage.setText("Relleno de Imagen");
        OpcionrellenoImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionrellenoImageActionPerformed(evt);
            }
        });
        jPanel1.add(OpcionrellenoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 160, -1));

        OpcionRellenoDeg.setText("Relleno Con Degradado");
        OpcionRellenoDeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionRellenoDegActionPerformed(evt);
            }
        });
        jPanel1.add(OpcionRellenoDeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        Opcionrelleno.setSelected(true);
        Opcionrelleno.setText("Relleno");
        Opcionrelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionrellenoActionPerformed(evt);
            }
        });
        jPanel1.add(Opcionrelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Imagen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dirección");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 270, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Degradado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 270, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Relleno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, -1));

        jButton1.setText("Elegir color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, -1));

        PrevisualizarColor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PrevisualizarColorLayout = new javax.swing.GroupLayout(PrevisualizarColor);
        PrevisualizarColor.setLayout(PrevisualizarColorLayout);
        PrevisualizarColorLayout.setHorizontalGroup(
            PrevisualizarColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PrevisualizarColorLayout.setVerticalGroup(
            PrevisualizarColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(PrevisualizarColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 40, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horizontal", "Vertical", "Diagonal", "Circular", "Radial" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 300, -1));

        jButton2.setText("Color Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        jButton3.setText("Color Fin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, 30));

        javax.swing.GroupLayout PFinLayout = new javax.swing.GroupLayout(PFin);
        PFin.setLayout(PFinLayout);
        PFinLayout.setHorizontalGroup(
            PFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PFinLayout.setVerticalGroup(
            PFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(PFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 40, 40));

        javax.swing.GroupLayout PIncioLayout = new javax.swing.GroupLayout(PIncio);
        PIncio.setLayout(PIncioLayout);
        PIncioLayout.setHorizontalGroup(
            PIncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PIncioLayout.setVerticalGroup(
            PIncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(PIncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 40, 40));

        jButton4.setText("Elegir Imagen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 270, -1));

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionrellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionrellenoActionPerformed
        drawPanel.setRelleno(Opcionrelleno.isSelected());
        drawPanel.repaint();
    }//GEN-LAST:event_OpcionrellenoActionPerformed

    private void OpcionRellenoDegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionRellenoDegActionPerformed
        drawPanel.getAtributosActuales().setRellenoDegradado(OpcionRellenoDeg.isSelected());
        drawPanel.repaint();
    }//GEN-LAST:event_OpcionRellenoDegActionPerformed

    private void OpcionrellenoImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionrellenoImageActionPerformed
        boolean activado = OpcionrellenoImage.isSelected();
        if (OpcionrellenoImage.isSelected()) {
            OpcionRellenoDeg.setSelected(false);
            drawPanel.getAtributosActuales().setRellenoImagenActivo(activado);
            drawPanel.repaint();
        }
       
    }//GEN-LAST:event_OpcionrellenoImageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Color color = JColorChooser.showDialog(this, "Color de Relleno", Color.WHITE);
        if (color != null) {
            drawPanel.setColorRelleno(color);
            PrevisualizarColor.setBackground(color);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        drawPanel.getAtributosActuales().setDireccionDegradado(jComboBox1.getSelectedIndex());
        drawPanel.repaint();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Color color = JColorChooser.showDialog(this, "Color inicio degradado", Color.WHITE);
        if (color != null) {
            drawPanel.getAtributosActuales().setColorDegradadoInicio(color);
            PIncio.setBackground(color);
            drawPanel.repaint();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Color color = JColorChooser.showDialog(this, "Color fin degradado", Color.BLUE);
        if (color != null) {
            drawPanel.getAtributosActuales().setColorDegradadoFin(color);
            PFin.setBackground(color);
            drawPanel.repaint();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));
            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                drawPanel.cargarImagenRelleno(fileChooser.getSelectedFile());
                OpcionrellenoImage.setVisible(true);
                //sliderEscalaImagen.setEnabled(true);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relleno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relleno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relleno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relleno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox OpcionRellenoDeg;
    private javax.swing.JCheckBox Opcionrelleno;
    private javax.swing.JCheckBox OpcionrellenoImage;
    private javax.swing.JPanel PFin;
    private javax.swing.JPanel PIncio;
    private javax.swing.JPanel PrevisualizarColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
